version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgresdb
      DATABASE_NAME: homie_production
      RAILS_LOG_TO_STDOUT: "true" 
      RAILS_SERVE_STATIC_FILES: "true"