version: '3'

services:
  dashboard:
    build: .
    restart: always
    networks:
      - web 
    ports:
      - "${PORT}:3000"
    labels:
      - traefik.http.routers.dashboard.rule=Host(`dashboard.deimel.de`)
      - traefik.http.services.dashboard.loadbalancer.server.port=3000
    env_file:
      - .env
networks:
  web:
    external: true
