name: build multi arch images 

on:
  push:
    branches: master

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.6.2
        with:
          buildx-version: latest
      - name: Build Dockerfile and push to DockerHub
        run: |
          REPO_NAME="stereosupersonic/homie"
          docker buildx build \
            -t ${REPO_NAME}:latest -t ${REPO_NAME}:${GITHUB_SHA} \
            --progress plain \
            --push \
            --platform linux/amd64,linux/arm64 .
